In [ ]:
#  Code for measuring  Urdu Dataset accuracy

import nltk 
#nltk.download('punkt')
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize

import spacy

#nlp = spacy.load("en_core_web_sm")
nlp = spacy.load('ur_model')

# import spacy
# nlp = spacy.load("en_core_web_sm")

# opening the file in read mode of stop words
my_file = open("stopwords-ur.txt", "r", encoding="utf8")
data = my_file.read()
urdu_stop_words = data.split("\n")
#print(urdu_stop_words)
# my_file.close()


import pandas as pd
# import os
# import csv
# file = pd.read_csv("URDU DATASET.csv")
# file.columns

correct = 1
for i in range(50):
    # p = output.Paragraphs[i]
    # q = output.Questions[i]
    # a = output.Answers[i]

    p = "جون 2005 میں ڈیسٹینی چائلڈ کے خاتمے کے بعد، اس نے اپنا دوسرا سولو البم، B&#39;Day (2006) ریلیز کیا، جس میں &quot;Déjà Vu&quot;، &quot;Irreplaceable&quot;، اور &quot;Beautiful Liar&quot; شامل تھے۔ بیونسے نے ڈریم گرلز (2006) میں گولڈن گلوب کے لیے نامزد کردہ پرفارمنس کے ساتھ، اور دی پنک پینتھر (2006) اور آبسیڈ (2009) میں اداکاری کے ساتھ اداکاری کا بھی آغاز کیا۔ ریپر جے زیڈ کے ساتھ اس کی شادی اور کیڈیلک ریکارڈز (2008) میں ایٹا جیمز کی تصویر کشی نے اس کے تیسرے البم I Am... Sasha Fierce (2008) کو متاثر کیا، جس میں اس کی الٹر ایگو ساشا فیرس کی پیدائش ہوئی اور اس نے ریکارڈ قائم کیا۔ 2010 میں چھ گریمی ایوارڈز، بشمول &quot;سنگل لیڈیز (پٹ اے رنگ آن اٹ)&quot; کے لیے سال کا بہترین گانا۔ بیونس نے 2010 میں موسیقی سے وقفہ لیا اور اپنے کیریئر کا انتظام سنبھال لیا۔ اس کا چوتھا البم 4 (2011) بعد میں 1970 کی دہائی کے فنک، 1980 کی دہائی کے پاپ، اور 1990 کی دہائی کی روح کو تلاش کرنے والے لہجے میں زیادہ مدھر تھا۔ اس کا تنقیدی طور پر سراہا جانے والا پانچواں اسٹوڈیو البم، بیونس (2013)، اس کی تجرباتی تیاری اور گہرے موضوعات کی تلاش کے ذریعے پچھلی ریلیز سے ممتاز تھا۔"
    q = "بیونس نے کس فنکار سے شادی کی؟" 
    # a = file.Answers[i]
    
    
#     TOKENIZATION OF PARAGRAPH AND REMOVING STOP WORDS
    word_tokens = word_tokenize(p)
    filtered_sentence = [w for w in word_tokens if not w.lower() in urdu_stop_words]
    filtered_sentence = []
    for w in word_tokens:
        if w not in urdu_stop_words:
            filtered_sentence.append(w)
#     print(filtered_sentence)
#     print("=====================2")
    mystring = ' '.join(map(str,filtered_sentence))
#     print(mystring)
    splitted_sen = mystring.split('۔')
#     print(splitted_sen)
    

#    TOKENIZATION OF SENTENCE AND REMOVING STOP WORDS
    word_tokens = word_tokenize(q)
    filtered_question = [w for w in word_tokens if not w.lower() in urdu_stop_words]
    filtered_question = []
    for t in word_tokens:
        if t not in urdu_stop_words:
            filtered_question.append(t)
    #print(filtered_question)

    string = ' '.join(map(str,filtered_question))
    #print(mystring)
    splitted_ques = string.split('۔')
    for i in splitted_ques:
        pass
        #print(i)

    #closing the stop words file 
    my_file.close()



    # Cosine Similarity of sentences list 
    csl = []
    # print(len(a_list))
    for i in (splitted_sen):
        
        cosine_similarity = nlp(i).similarity(nlp(splitted_ques[0]))
        csl.append(cosine_similarity)
#     print(csl)



    res = {}
    for key in splitted_sen:
        for value in csl:
            res[key] = value
            csl.remove(value)
            break  

    # Printing resultant dictionary 
#     print ("Resultant dictionary is : " +  str(res))

    fin_max = max(res, key=res.get)
#     All ANSWERS
#     print("Question: " + q)
#     print("Maximum value:",fin_max)

    if a in  fin_max:
        correct += 1
#         Correct Answers
        print("Actual Answer =="+a)
        print("Predicted Answer  =="+fin_max)
    else:
        pass

print(correct)
# print("Accuracy in %",((correct/10000)*100))

FileNotFoundError: [Errno 2] No such file or directory: 'stopwords-ur.txt'

In [ ]:
import pandas as pd
output = pd.read_csv("urdudatatest.csv")

In [ ]:
output.head()

,Column1,Paragraphs,Questions,Answers,Column2
0,0,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,بیونس کا مقبول ہونا کب شروع ہوا؟,1990 کی دہائی کے آخر میں,","
1,1,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,بیونس نے کن شعبوں میں مقابلہ کیا جب وہ بڑی ہو ...,گانا اور ناچنا,NaN
2,2,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,بیونس نے قسمت کا بچہ کب چھوڑا اور سولو گلوکار ...,2003,NaN
3,3,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,بیونس کس شہر اور ریاست میں پلا بڑھا؟,ہیوسٹن، ٹیکساس,NaN
4,4,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,بیونس کس دہائی میں مشہور ہوئی؟,1990 کی دہائی کے آخر میں,NaN

In [ ]:
import pandas as pd
output = pd.read_csv("urdudatatest.csv")
output.head()

# import pandas as pd
output = pd.read_csv("urdudatatest.csv")
delete = 0
for i in range(30):
    p = output.Paragraphs[i]
#     print(p)
    #     q = file.Questions[i]
    a = output.Answers[i]
#     print(a)
#     output.drop([1,5],axis=0,inplace=True)
    
    if a not in p:
        output.drop(i,axis=0,inplace=True)
        print("=========DELETED==========")
        delete += 1
    else:
        print("=========NOT DELETED==========")
print(delete)
output.head(30)

=========NOT DELETED==========
=========DELETED==========
=========NOT DELETED==========
=========NOT DELETED==========
=========NOT DELETED==========
=========DELETED==========
=========DELETED==========
=========DELETED==========
=========NOT DELETED==========
=========DELETED==========
=========DELETED==========
=========NOT DELETED==========
=========NOT DELETED==========
=========DELETED==========
=========DELETED==========
=========NOT DELETED==========
=========NOT DELETED==========
=========NOT DELETED==========
=========DELETED==========
=========NOT DELETED==========
=========NOT DELETED==========
=========NOT DELETED==========
=========DELETED==========
=========DELETED==========
=========DELETED==========
=========NOT DELETED==========
=========NOT DELETED==========
=========DELETED==========
=========NOT DELETED==========
=========NOT DELETED==========
13

In [ ]:
output.head(30)

,Column1,Paragraphs,Questions,Answers,Column2
0,0,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,بیونس کا مقبول ہونا کب شروع ہوا؟,1990 کی دہائی کے آخر میں,","
2,2,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,بیونس نے قسمت کا بچہ کب چھوڑا اور سولو گلوکار ...,2003,NaN
3,3,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,بیونس کس شہر اور ریاست میں پلا بڑھا؟,ہیوسٹن، ٹیکساس,NaN
4,4,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,بیونس کس دہائی میں مشہور ہوئی؟,1990 کی دہائی کے آخر میں,NaN
8,8,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,بیونس کب شہرت میں پہنچی؟,1990 کی دہائی کے آخر میں,NaN
11,11,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,بیونس نے ڈینجرسلی ان لو کو کب ریلیز کیا؟,2003,NaN
12,12,Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...,بیونس نے اپنے پہلے سولو البم کے لیے کتنے گریمی...,پانچ,NaN
15,15,جون 2005 میں ڈیسٹینی چائلڈ کے خاتمے کے بعد، اس...,اپنے دوسرے سولو البم کے بعد، بیونس نے کون سا ت...,اداکاری,NaN
16,16,جون 2005 میں ڈیسٹینی چائلڈ کے خاتمے کے بعد، اس...,بیونس نے کس فنکار سے شادی کی؟,جے زیڈ,NaN
17,17,جون 2005 میں ڈیسٹینی چائلڈ کے خاتمے کے بعد، اس...,گرامیز کا ریکارڈ قائم کرنے کے لیے، بیونس نے کت...,چھ,NaN
19,19,جون 2005 میں ڈیسٹینی چائلڈ کے خاتمے کے بعد، اس...,بیونس نے اپنے کیرئیر میں کب وقفہ لیا اور اپنے ...,2010,NaN
20,20,جون 2005 میں ڈیسٹینی چائلڈ کے خاتمے کے بعد، اس...,اس کے پچھلے کام سے کون سا البم زیادہ گہرا تھا؟,بیونس,NaN
21,21,جون 2005 میں ڈیسٹینی چائلڈ کے خاتمے کے بعد، اس...,ایٹا جیمز کو کس فلم میں پیش کرنے کے بعد، کیا ب...,کیڈیلک ریکارڈز,NaN
25,25,جون 2005 میں ڈیسٹینی چائلڈ کے خاتمے کے بعد، اس...,بیونس کی شادی کس سے ہوئی؟,جے زیڈ,NaN
26,26,جون 2005 میں ڈیسٹینی چائلڈ کے خاتمے کے بعد، اس...,بیونس کی تبدیلی انا کا نام کیا ہے؟,ساشا فیرس,NaN
28,28,ایک خود سے بیان کردہ &quot;جدید دور کی نسائی م...,ٹائم میگزین نے انہیں صدی کے سب سے زیادہ 100 لو...,بااثر,NaN
29,29,ایک خود سے بیان کردہ &quot;جدید دور کی نسائی م...,کس میگزین نے انہیں سب سے غالب خاتون موسیقار قر...,فوربس,NaN
30,30,ایک خود سے بیان کردہ &quot;جدید دور کی نسائی م...,امریکہ کی ریکارڈنگ انڈسٹری ایسوسی ایشن نے کس د...,2000 کی دہائی,NaN
31,31,ایک خود سے بیان کردہ &quot;جدید دور کی نسائی م...,کس میگزین نے بیونس کو 2015 میں سب سے طاقتور خا...,فوربس,NaN
32,32,ایک خود سے بیان کردہ &quot;جدید دور کی نسائی م...,بیونس نے خود کو ایک نسائی ماہر کے طور پر کیسے ...,جدید دور کی نسائی ماہر,NaN
33,33,ایک خود سے بیان کردہ &quot;جدید دور کی نسائی م...,کن سالوں میں ٹائم نے بیونس کو دنیا کے 100 بااث...,2013 اور 2014,NaN
34,34,ایک خود سے بیان کردہ &quot;جدید دور کی نسائی م...,بیونس نے اپنے 19 سالہ کیریئر میں کتنے ریکارڈ ف...,118 ملین,NaN
35,35,ایک خود سے بیان کردہ &quot;جدید دور کی نسائی م...,Beyoncé نے Destiny&#39;s Child کے حصے کے طور پ...,60 ملین,NaN
36,36,ایک خود سے بیان کردہ &quot;جدید دور کی نسائی م...,Destiny&#39;s Child کو چھوڑنے کے بعد، Beyoncé ...,118 ملین,NaN
37,37,ایک خود سے بیان کردہ &quot;جدید دور کی نسائی م...,بیونس نے کتنے گریمی ایوارڈز جیتے ہیں؟,20,NaN
38,38,ایک خود سے بیان کردہ &quot;جدید دور کی نسائی م...,کس میگزین نے بیونسے کو 2015 کی سب سے طاقتور خا...,فوربس,NaN
39,39,Beyoncé Giselle Knowles کی پیدائش ہیوسٹن، ٹیکس...,بیونس کی چھوٹی بہن نے بھی اس کے ساتھ کس بینڈ م...,تقدیر کا بچہ,NaN
40,40,Beyoncé Giselle Knowles کی پیدائش ہیوسٹن، ٹیکس...,بیونس کا نام کہاں سے آیا؟,اس کی ماں کا پہلا نام,NaN
41,41,Beyoncé Giselle Knowles کی پیدائش ہیوسٹن، ٹیکس...,بیونس کے والد کونسی نسل تھی؟,افریقی امریکی,NaN
42,42,Beyoncé Giselle Knowles کی پیدائش ہیوسٹن، ٹیکس...,بیونس کا بچپن گھر کس مذہب پر یقین رکھتا تھا؟,میتھوڈسٹ,NaN